In [18]:
pwd

'/Users/ariedamuco/Dropbox (CEU Econ)/TextAnalysisCEU'

In [19]:
import os

In [20]:
os.chdir("/Users/ariedamuco/Dropbox (CEU Econ)/TextAnalysisCEU")

In [21]:
nltk= open("Inputs/nltk_stopwords.txt", 'r')

In [22]:
nltk

In [23]:
nltk_stopwords = []

In [24]:
nltk_stopwords

[]

In [25]:
for i in nltk.readlines():
    i = i.replace("\n","")
    nltk_stopwords.append(i)

In [26]:
print(nltk_stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [27]:
import pandas as pd
europe = pd.read_html("https://insights.invyo.io/europe/mapping/the-european-top-50-of-the-most-valued-fintech/")

In [28]:
type(europe)

list

In [30]:
len(europe)

1

In [31]:
top_fintec_europe = europe[0]

In [32]:
top_fintec_europe

,Ranking,Name,Valuation,Country,Sector,Variation
0,1,Adyen,$8.3B,Netherlands,Payment,0
1,2,Nexi,$8.2B,Italy,"Payment, Loyalty, Transfer, Fx",0
2,3,Klarna,$5.5B,Sweden,Payment,0
3,4,Greensill,$3.5B,UK,Fundings,0
4,5,Transferwise,$3.5B,UK,Payment,0
5,6,N26,$3.5B,Germany,Neobank,0
6,7,Oaknorth,$2.8B,UK,Neobank,0
7,8,Monzo,$2.5B,UK,Neobank,0
8,9,Funding Circle,$2.4B,UK,Lending,0
9,10,Izettle,$2.2B,Sweden,Payment,0
10,11,Checkout,$2B,UK,Payment,0
11,12,Darktrace,$1.7B,UK,Regtech,0
12,13,Revolut,$1.7B,UK,Neobank,0
13,14,Sumup,>$1.0B,UK,Payment,0
14,15,Avaloq,$1.0B,Switzerland,Bank as a Service,0
15,16,Radius Payment,$1.0B,UK,Payment,0
16,17,Ivalua,$1.0B,France,Service to Finance,0
17,18,Numbrs,$1.0B,Switzerland,Neobank,0
18,19,Rapyd,>$900m,Rapyd,Payment,31
19,20,Worldremit,>$900m,UK,Payment,0
20,21,Wefox,>$700m,Germany,Insurtech,0
21,22,Starling Bank,>$600m,UK,Neobank,5
22,23,Atom Bank,$590m,UK,Neobank,0
23,24,Feedzai,$575m,Portugal,Regtech,0
24,25,Raisin,>$550m,Germany,Personal & Business cash management,0
25,26,Tradeplus24,>$550m,Switzeland,Lending,0
26,27,Zopa,$550m,UK,Lending,0
27,28,Deposit Solutions,$500M,Germany,Bank as a Service,0
28,29,Pleo,$ 500m,Denmark,Payment,0
29,30,Smava,$ 500m,Germany,Lending,0
30,31,Kreditech,NaN,Germany,Lending,0
31,32,Pagantis,>$400m,Spain,Payment,0
32,33,Gocardless,>$400m,UK,Payment,0
33,34,Wynd,>$400m,France,Payment,0
34,35,Moneyfarm,>$400m,Italy,Wealthtech,7
35,36,Ratesetter,$360m,UK,Lending,0
36,37,Tinubu Square,>$350m,France,Regtech,0
37,38,Ebury,>$350m,UK,Paiement,0
38,39,Bitstamp,$350m,UK,Crypto,0
39,40,Nutmeg,$317m,UK,WealthTech,0
40,41,Solaris Bank,>$300m,Germany,Bank as a Service,0
41,42,Monese,>$300m,UK,Neobank,0
42,43,Ledger,$300m,France,Crypto,0
43,44,Banking Circle,$300m,Denmark,Payment,0
44,45,BIMA,$300m,Sweden,Insurtech,0
45,46,PayFit,>$280m,France,Service to Finance,0
46,47,Tink,$270m,Sweden,Bank as a Service,0
47,48,Alan,>$250m,France,InsurTech,0
48,49,Younited Credit,>$250m,France,Lending,0
49,50,Curve,>$250m,UK,Service to Finance,0